// apps/investment-calculator-angular/src/app/results-table/results-table.component.ts
import { ChangeDetectionStrategy, Component, input, InputSignal } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  calculateTotalInterest,
  InvestmentRecord,
  totalCapitalInvestment,
} from '@gv-frameworks-battle/investment-calculator-domain';

@Component({
  selector: 'app-results-table',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './results-table.component.html',
  styleUrl: './results-table.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ResultsTableComponent {
  protected readonly calculateTotalInterest = calculateTotalInterest;
  protected readonly totalCapitalInvestment = totalCapitalInvestment;

  public data: InputSignal<InvestmentRecord[]> = input.required<InvestmentRecord[]>();
}

<table id="result">
  <thead>
  <tr>
    <th>Year</th>
    <th>Investment Value</th>
    <th>Interest (Year)</th>
    <th>Total Interest</th>
    <th>Invested Capital</th>
  </tr>
  </thead>
  <tbody>
    @for (record of data(); track record.year) {
      <tr>
        <td>{{ record.year }}</td>
        <td>{{ record.valueEndOfYear | currency:'USD':'symbol':'0.0-0' }}</td>
        <td>{{ record.interest | currency:'USD':'symbol':'0.0-0' }}</td>
        <td>{{ calculateTotalInterest(data(), record) | currency:'USD':'symbol':'0.0-0' }}</td>
        <td>{{ totalCapitalInvestment(data(), record) | currency:'USD':'symbol':'0.0-0' }}</td>
      </tr>
    }
  </tbody>
</table>

// apps/investment-calculator-react/src/app/results-table/results-table.tsx
import {
  calculateTotalInterest,
  formatter,
  InvestmentRecord,
  totalCapitalInvestment,
} from '@gv-frameworks-battle/investment-calculator-domain';

export function ResultsTable({ data }: { data: InvestmentRecord[] }) {
  return (
    <table id="result">
      <thead>
        <tr>
          <th>Year</th>
          <th>Investment Value</th>
          <th>Interest (Year)</th>
          <th>Total Interest</th>
          <th>Invested Capital</th>
        </tr>
      </thead>
      <tbody>
        {data.map((record) => (
          <tr key={record.year}>
            <td>{record.year}</td>
            <td>{formatter.format(record.valueEndOfYear)}</td>
            <td>{formatter.format(record.interest)}</td>
            <td>{formatter.format(calculateTotalInterest(data, record))}</td>
            <td>{formatter.format(totalCapitalInvestment(data, record))}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export default ResultsTable;
