// apps/tic-tac-toe-angular/src/app/game-over/game-over.component.ts
import { ChangeDetectionStrategy, Component, input, InputSignal, output, OutputEmitterRef } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-game-over',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './game-over.component.html',
  styleUrl: './game-over.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class GameOverComponent {
  public winner: InputSignal<string | undefined> = input.required<string | undefined>();

  public onRematch: OutputEmitterRef<void> = output<void>();
}

<div id="game-over">
  <h2>Game Over!</h2>

  @if(winner(); as winner) {
    <p>{{ winner }} won!</p>
  } @else {
    <p>It is a draw!</p>
  }

  <button (click)="onRematch.emit()">Rematch!</button>
</div>

// apps/tic-tac-toe-react/src/app/components/GameOver/GameOver.tsx
export default function GameOver({ winner, onRematch }: { winner: string | undefined, onRematch: () => void }) {
  return (
          <div id="game-over">
            <h2>Game Over!</h2>
            { winner ? <p>{ winner } won!</p> : <p>It is a draw!</p> }
            <p>
              <button onClick={ () => {
                if (onRematch) onRematch();
              } }>Rematch!
              </button>
            </p>
          </div>
  );
}
