// apps/tic-tac-toe-react/src/app/App.tsx
import Player from './components/Player/Player';
import GameBoard from './components/GameBoard/GameBoard';
import { useState } from 'react';
import Log from './components/Log/Log';
import GameOver from './components/GameOver/GameOver';
import {
  deriveActivePlayer,
  GameBoardGrid,
  GameTurn,
  getWinner,
  INITIAL_PLAYERS,
  initializeNewBoard,
  PlayerSymbol,
} from '@gv-frameworks-battle/tic-tac-toe-domain';

export function App() {
  const [players, setPlayers] = useState(INITIAL_PLAYERS);
  const [gameTurns, setGameTurns] = useState<GameTurn[]>([]);
  const gameBoard: GameBoardGrid = initializeNewBoard(gameTurns);
  const activePlayer: PlayerSymbol = deriveActivePlayer(gameTurns);
  const winner: PlayerSymbol | undefined = getWinner(gameBoard);
  const isDraw: boolean = gameTurns.length === 9 && !winner;

  function handleRematch(): void {
    setGameTurns([]);
  }

  function handleSelectSquare(rowIdx: number, colIdx: number): void {
    setGameTurns((prevState: GameTurn[]) => {
      const activePlayer = deriveActivePlayer(prevState);

      return [{ player: activePlayer, square: { row: rowIdx, col: colIdx } }, ...prevState];
    });
  }

  function handlePlayerChanged(symbol: PlayerSymbol, name: string): void {
    setPlayers((prevState) => {
      const newPlayers = { ...prevState };
      newPlayers[symbol] = name;

      return newPlayers;
    });
  }

  return (
    <>
      <header>
        <img src="/game-logo.png" alt="Hand-drawn tic tac toe board" />
        <h1>React Tic-Tac-Toe</h1>
      </header>

      <main>
        <div id="game-container">
          <ol id="players" className="highlight-player">
            <Player
              name={players[PlayerSymbol.X]}
              symbol={PlayerSymbol.X}
              isActive={activePlayer === PlayerSymbol.X}
              onNameChanged={(name) => handlePlayerChanged(PlayerSymbol.X, name)}
            />

            <Player
              name={players[PlayerSymbol.O]}
              symbol={PlayerSymbol.O}
              isActive={activePlayer === PlayerSymbol.O}
              onNameChanged={(name) => handlePlayerChanged(PlayerSymbol.O, name)}
            />
          </ol>

          {(winner || isDraw) && (
            <GameOver winner={winner ? players[winner] : undefined} onRematch={handleRematch}></GameOver>
          )}

          <GameBoard gameBoard={gameBoard} onSelectSquare={handleSelectSquare} />
        </div>

        <Log gameTurns={gameTurns} />
      </main>
    </>
  );
}

export default App;

// apps/tic-tac-toe-angular/src/app/app.component.ts
import { ChangeDetectionStrategy, Component, computed, Signal, signal, WritableSignal } from '@angular/core';
import {
  deriveActivePlayer,
  GameBoardGrid,
  GameTurn,
  getWinner,
  INITIAL_PLAYERS,
  initializeNewBoard,
  Players,
  PlayerSymbol
} from "@gv-frameworks-battle/domain";
import { PlayerComponent } from "./player/player.component";
import { NgClass } from "@angular/common";
import { GameBoardComponent } from "./game-board/game-board.component";
import { LogComponent } from "./log/log.component";
import { GameOverComponent } from "./game-over/game-over.component";

@Component({
  standalone: true,
  imports: [
    PlayerComponent,
    NgClass,
    GameBoardComponent,
    LogComponent,
    GameOverComponent
  ],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  protected readonly PlayerSymbol = PlayerSymbol;

  protected players: WritableSignal<Players> = signal(INITIAL_PLAYERS);
  protected gameTurns: WritableSignal<GameTurn[]> = signal<GameTurn[]>([]);
  protected gameBoard: Signal<GameBoardGrid> = computed(() => initializeNewBoard(this.gameTurns()));
  protected activePlayer: Signal<PlayerSymbol> = computed(() => deriveActivePlayer(this.gameTurns()))
  protected winner: Signal<PlayerSymbol | undefined> = computed(() => getWinner(this.gameBoard()));
  protected winnerName: Signal<string | undefined> = computed(() => {
    const symbol = this.winner();
    if (!symbol) {
      return undefined;
    }

    return this.players()[symbol];
  });
  protected isDraw: Signal<boolean> = computed(() => this.gameTurns().length === 9 && !this.winner());

  protected onPlayerNameChanged(symbol: PlayerSymbol, newName: string): void {
    this.players.update((prev) => {
      return {
        ...prev,
        [symbol]: newName,
      };
    })
  }

  protected onSquareSelected(event: { rowIndex: number; colIndex: number }): void {
    this.gameTurns.update((prev) => {
      return [
        { player: this.activePlayer(), square: { row: event.rowIndex, col: event.colIndex } },
        ...prev,
      ];
    });
  }

  protected startNewGame(): void {
    this.gameTurns.set([]);
  }
}

<header>
  <img src="/tic-tac-toe-angular-assets/game-logo.png" alt="Hand-drawn tic tac toe board"/>
  <h1>Angular Tic-Tac-Toe</h1>
</header>

<main>
  <div id="game-container">
    <ol id="players" class="highlight-player">
      <li [ngClass]="{active: activePlayer() === PlayerSymbol.X}">
        <app-player
                [symbol]="PlayerSymbol.X"
                [name]="players().X"
                (nameChanged)="onPlayerNameChanged(PlayerSymbol.X, $event)"
        ></app-player>
      </li>

      <li [ngClass]="{active: activePlayer() === PlayerSymbol.O}">
        <app-player
                [symbol]="PlayerSymbol.O"
                [name]="players().O"
                (nameChanged)="onPlayerNameChanged(PlayerSymbol.O, $event)"
        ></app-player>
      </li>
    </ol>

    @if (winner() || isDraw()) {
      <app-game-over [winner]="winnerName()" (onRematch)="startNewGame()"></app-game-over>
    }

    <app-game-board [gameBoard]="gameBoard()" (squareSelected)="onSquareSelected($event)"></app-game-board>
  </div>

  <app-log [gameTurns]="gameTurns()"></app-log>
</main>
