// apps/tic-tac-toe-react/src/app/components/Player/Player.tsx
import { ChangeEvent, useState } from 'react';
import { PlayerSymbol } from '@gv-frameworks-battle/tic-tac-toe-domain';

export default function Player({
  name,
  symbol,
  isActive,
  onNameChanged,
}: {
  name: string;
  symbol: PlayerSymbol;
  isActive: boolean;
  onNameChanged: (name: string) => void;
}) {
  const [playerName, setPlayerName] = useState(name);
  const [isEditing, setIsEditing] = useState(false);

  let buttonLabel = 'Edit';
  if (isEditing) {
    buttonLabel = 'Save';
  }

  function handleBtnClick() {
    setIsEditing((prevState) => !prevState);

    if (onNameChanged) {
      onNameChanged(playerName);
    }
  }

  function handlePlayerNameChange(event: ChangeEvent<HTMLInputElement>): void {
    const newName = event.target.value;

    setPlayerName(newName);
  }

  return (
    <li className={isActive ? 'active' : undefined}>
      <span className="player">
        {isEditing ? (
          <input type="text" required value={playerName} onChange={(e) => handlePlayerNameChange(e)} />
        ) : (
          <span className="player-name">{playerName}</span>
        )}
        <span className="player-symbol">{symbol}</span>
      </span>
      <button onClick={handleBtnClick}>{buttonLabel}</button>
    </li>
  );
}

// apps/tic-tac-toe-angular/src/app/player/player.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  HostBinding,
  input,
  InputSignal,
  OnChanges,
  output,
  OutputEmitterRef,
  signal,
} from '@angular/core';
import { PlayerSymbol } from '@gv-frameworks-battle/tic-tac-toe-domain';
import { FormControl, ReactiveFormsModule } from '@angular/forms';

@Component({
  selector: 'app-player',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './player.component.html',
  styleUrl: './player.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlayerComponent implements OnChanges {
  public name: InputSignal<string> = input.required<string>();
  public symbol: InputSignal<PlayerSymbol> = input.required<PlayerSymbol>();

  public nameChanged: OutputEmitterRef<string> = output<string>();

  protected isEditing = signal<boolean>(false);
  protected buttonLabel = computed(() => (this.isEditing() ? 'Save' : 'Edit'));

  protected formControl = new FormControl<string>('');

  @HostBinding('style.display') private displayStyle = 'flex';

  public ngOnChanges(): void {
    this.formControl.setValue(this.name());
  }

  protected onEditClick(): void {
    if (this.isEditing()) {
      const newName = this.formControl.value ?? '';

      this.nameChanged.emit(newName);
    }

    this.isEditing.update((prev) => !prev);
  }
}

<span class="player">
  @if (isEditing()) {
    <input [formControl]="formControl" type="text" required/>
  } @else {
    <span class="player-name">{{ name() }}</span>
  }

  <span class="player-symbol">{{ symbol() }}</span>
</span>

<button (click)="onEditClick()">{{ buttonLabel() }}</button>
