// apps/investment-calculator-react/src/app/app.tsx
import './app.css';
import Header from './header/header';
import CalcForm from './calc-form/calc-form';
import ResultsTable from './results-table/results-table';

export function App() {
  return (
    <>
      <Header />
      <CalcForm />
      <ResultsTable />
    </>
  );
}

export default App;

// apps/investment-calculator-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from './header/header.component';
import { CalcFormComponent } from './calc-form/calc-form.component';
import { ResultsTableComponent } from './results-table/results-table.component';

@Component({
  standalone: true,
  imports: [HeaderComponent, CalcFormComponent, ResultsTableComponent],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {}

<app-header></app-header>

<app-calc-form></app-calc-form>

<app-results-table></app-results-table>
