// apps/styling-react/src/app/components/header.tsx
import logo from '../../assets/logo.png';
import classes from './header.module.css';

export default function Header() {
  return (
    <header>
      <img src={logo} alt="A canvas" />
      <h1>ReactArt</h1>
      <p className={classes.paragraph}>
        A community of artists and art-lovers.
      </p>
    </header>
  );
}

// apps/styling-angular/src/app/header/header.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderComponent {}

<header>
  <img src="/styling-angular-assets/logo.png" alt="A canvas" />
  <h1>AngularArt</h1>
  <p>A community of artists and art-lovers.</p>
</header>
