// apps/countdown-game-angular/src/app/app.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PlayerComponent } from './player/player.component';
import { TimerChallengeComponent } from './timer-challenge/timer-challenge.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, PlayerComponent, TimerChallengeComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {}

<div id="modal"></div>
<div id="content">
  <header>
    <h1>
      The <em>Almost</em> Final Countdown
    </h1>
    <p>Stop the timer once you estimate that time is (almost) up</p>
  </header>

  <app-player></app-player>

  <div id="challenges">
    <app-timer-challenge title="Easy" [targetTimeSecs]="1"></app-timer-challenge>
    <app-timer-challenge title="Not easy" [targetTimeSecs]="5"></app-timer-challenge>
    <app-timer-challenge title="Getting tough" [targetTimeSecs]="10"></app-timer-challenge>
    <app-timer-challenge title="Pros only" [targetTimeSecs]="15"></app-timer-challenge>
  </div>
</div>

// apps/countdown-game-react/src/app/app.tsx
import { createRoot } from 'react-dom/client';
import Player from './components/player';
import { AppContainer } from './app-container';
import TimerChallenge from './components/timer-challenge';

export function App() {
  return (
    <AppContainer>
      <div id="modal"></div>
      <div id="content">
        <header>
          <h1>
            The <em>Almost</em> Final Countdown
          </h1>
          <p>Stop the timer once you estimate that time is (almost) up</p>
        </header>

        <Player />

        <div id="challenges">
          <TimerChallenge title="Easy" targetTimeSecs={1} />
          <TimerChallenge title="Not easy" targetTimeSecs={5} />
          <TimerChallenge title="Getting tough" targetTimeSecs={10} />
          <TimerChallenge title="Pros only" targetTimeSecs={15} />
        </div>
      </div>
    </AppContainer>
  );
}

class CountdownGameReactAppElement extends HTMLElement {
  public connectedCallback(): void {
    console.warn('CountdownGameReactAppElement is connected: boostrap.tsx');

    // ReactDOM.render(<App />, this);
    const root = createRoot(this);
    root.render(<App />);
  }

  public disconnectedCallback(): void {
    console.warn('CountdownGameReactAppElement is disconnected: boostrap.tsx');
  }
}

customElements.define(
  'countdown-game-react-app-element',
  CountdownGameReactAppElement
);

export default App;
