// apps/tic-tac-toe-react/src/app/components/Log/Log.tsx
import { GameTurn } from '@gv-frameworks-battle/tic-tac-toe-domain';

export default function Log({ gameTurns = [] }: { gameTurns: GameTurn[] }) {
  return (
    <ol id="log">
      {gameTurns.map((oneTurn) => {
        return (
          <li key={oneTurn.square.row + '-' + oneTurn.square.col}>
            {oneTurn.player} selected {oneTurn.square.row}, {oneTurn.square.col}
          </li>
        );
      })}
    </ol>
  );
}

// apps/tic-tac-toe-angular/src/app/log/log.component.ts
import { ChangeDetectionStrategy, Component, input, InputSignal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GameTurn } from '@gv-frameworks-battle/tic-tac-toe-domain';

@Component({
  selector: 'app-log',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './log.component.html',
  styleUrl: './log.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LogComponent {
  public gameTurns: InputSignal<GameTurn[]> = input.required<GameTurn[]>();
}

<ol id="log">
  @for(oneTurn of gameTurns(); track oneTurn.square.row + '-' + oneTurn.square.col) {
    <li>
      {{ oneTurn.player }} selected {{ oneTurn.square.row }}, {{ oneTurn.square.col }}
    </li>
  }
</ol>
