// apps/investment-calculator-angular/src/app/calc-form/calc-form.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-calc-form',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './calc-form.component.html',
  styleUrl: './calc-form.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CalcFormComponent {}

<div id="user-input">
  <div class="input-group">
    <div>
      <label>Initial Investment</label>
      <input type="number" required/>
    </div>

    <div>
      <label>Annual Investment</label>
      <input type="number" required/>
    </div>
  </div>

  <div class="input-group">
    <div>
      <label>Expected Return</label>
      <input type="number" required/>
    </div>

    <div>
      <label>Duration</label>
      <input type="number" min="0" required/>
    </div>
  </div>
</div>

// apps/investment-calculator-react/src/app/calc-form/calc-form.tsx
export function CalcForm() {
  return (
    <div id="user-input">
      <div className="input-group">
        <div>
          <label>Initial Investment</label>
          <input type="number" required />
        </div>

        <div>
          <label>Annual Investment</label>
          <input type="number" required />
        </div>
      </div>

      <div className="input-group">
        <div>
          <label>Expected Return</label>
          <input type="number" required />
        </div>

        <div>
          <label>Duration</label>
          <input type="number" required />
        </div>
      </div>
    </div>
  );
}

export default CalcForm;
