// apps/countdown-game-react/src/app/components/result-modal.tsx
import { ForwardedRef, forwardRef, useImperativeHandle, useRef } from 'react';

export interface ResultModalProps {
  targetTimeMillis: number;
  remainingTimeMillis?: number;
}

export interface ResultModalRef {
  open: () => void;
  close: () => void;
}

export default forwardRef(function ResultModal(
  { targetTimeMillis, remainingTimeMillis }: ResultModalProps,
  ref: ForwardedRef<ResultModalRef>
) {
  const targetTimeSecs = +(targetTimeMillis / 1000).toFixed(0);
  const dialog = useRef<HTMLDialogElement>(null);
  let result: 'won' | 'lost' | undefined;
  if (remainingTimeMillis !== undefined) {
    result = remainingTimeMillis <= 0 ? 'lost' : 'won';
  }

  let remainingSeconds: number | undefined;
  if (!remainingTimeMillis || remainingTimeMillis < 0) {
    remainingSeconds = 0;
  } else {
    remainingSeconds = +(remainingTimeMillis / 1000).toFixed(2);
  }

  const score = Math.round(
    (1 - (remainingTimeMillis ?? targetTimeMillis) / targetTimeMillis) * 100
  );

  useImperativeHandle(ref, (): ResultModalRef => {
    return {
      open(): void {
        dialog.current?.showModal();
      },
      close(): void {
        dialog.current?.close();
      },
    };
  });

  return (
    <dialog ref={dialog} className="result-modal">
      {result === 'lost' && <h2>You lost</h2>}
      {result !== 'lost' && <h2>Your Score: {score}</h2>}

      <p>
        The target time was{' '}
        <strong>
          {targetTimeSecs} second{targetTimeSecs === 1 ? '' : 's'}.
        </strong>
      </p>

      <p>
        You stopped the timer with{' '}
        <strong>{remainingSeconds} seconds left.</strong>
      </p>

      <form method="dialog">
        <button>Close</button>
      </form>
    </dialog>
  );
});

// apps/countdown-game-angular/src/app/result-modal/result-modal.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-result-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './result-modal.component.html',
  styleUrl: './result-modal.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ResultModalComponent {
  public targetTimeMillis = input.required<number>();
  public remainingTimeMillis = input<number | undefined>(undefined);

  protected result = computed(() => {
    const remainingTimeMillis = this.remainingTimeMillis();
    if (remainingTimeMillis === undefined) {
      return undefined;
    }

    return remainingTimeMillis <= 0 ? 'lost' : 'won';
  });

  protected targetTimeSecs = computed(
    () => +(this.targetTimeMillis() / 1000).toFixed(2)
  );

  protected remainingSeconds = computed(() => {
    let remainingSeconds = 0;
    const remainingTimeMillis = this.remainingTimeMillis();
    if (remainingTimeMillis && remainingTimeMillis >= 0) {
      remainingSeconds = +(remainingTimeMillis / 1000).toFixed(2);
    }

    return remainingSeconds;
  });

  protected score = computed(() => {
    let remainingTimeMillis = this.remainingTimeMillis();
    remainingTimeMillis = remainingTimeMillis ?? this.targetTimeMillis();

    return Math.round(
      (1 - remainingTimeMillis / this.targetTimeMillis()) * 100
    );
  });

  @ViewChild('dialog') private dialog!: ElementRef<HTMLDialogElement>;

  public open(): void {
    this.dialog.nativeElement.showModal();
  }

  public close(): void {
    this.dialog.nativeElement.close();
  }
}

<dialog #dialog class="result-modal">
  @if (result() === 'lost') {
    <h2>You lost</h2>
  } @else if (result() !== 'lost') {
    <h2>Your Score: {{ score() }}</h2>
  }

  <p>
    The target time was
    <strong>{{ targetTimeSecs() }} second{{ targetTimeSecs() === 1 ? '' : 's' }}</strong>
  </p>

  <p>
    You stopped the timer with
    <strong>{{ remainingSeconds() }} seconds left.</strong>
  </p>

  <form method="dialog">
    <button>Close</button>
  </form>
</dialog>
