// src/components/GameBoard/GameBoard.jsx
export default function GameBoard({gameBoard = [], onSelectSquare}) {
  function handleSelectSquare(rowIdx, colIdx) {
    if (gameBoard[rowIdx][colIdx]) {
      // This cell is already marked by user
      return;
    }

    if (onSelectSquare) {
      onSelectSquare(rowIdx, colIdx);
    }
  }

  return (
    <ol id="game-board">
      {
        gameBoard.map((row, rowIndex) => {
          return <li key={rowIndex}>
            <ol>{
              row.map((playerSymbol, colIndex) => {
                return <li key={colIndex}>
                  <button onClick={() => handleSelectSquare(rowIndex, colIndex)} disabled={!!playerSymbol}>
                    {playerSymbol}
                  </button>
                </li>
              })
            }</ol>
          </li>
        })
      }
    </ol>
  );
}

// apps/tic-tac-toe-angular/src/app/game-board/game-board.component.ts
import { ChangeDetectionStrategy, Component, input, InputSignal, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GameBoardGrid } from "@gv-frameworks-battle/domain";

@Component({
  selector: 'app-game-board',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './game-board.component.html',
  styleUrl: './game-board.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class GameBoardComponent {
  public gameBoard: InputSignal<GameBoardGrid> = input.required<GameBoardGrid>();

  public squareSelected = output<{ rowIndex: number, colIndex: number }>();

  public handleSelectSquare(rowIndex: number, colIndex: number): void {
    if (this.gameBoard()[rowIndex][colIndex]) {
      // This cell is already marked by user
      return;
    }

    this.squareSelected.emit({
      rowIndex: rowIndex,
      colIndex: colIndex,
    })
  }
}

<ol id="game-board">
  @for (row of gameBoard(); let rowIndex = $index; track rowIndex) {
    <li>
      <ol>
        @for (playerSymbol of row; let colIndex = $index; track colIndex) {
          <li>
            <button (click)="handleSelectSquare(rowIndex, colIndex)">{{ playerSymbol }}</button>
          </li>
        }
      </ol>
    </li>
  }
</ol>
