// apps/countdown-game-angular/src/app/player/player.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-player',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './player.component.html',
  styleUrl: './player.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlayerComponent {
  protected playerName?: string;
}

<section id="player">
  <h2>Welcome {{ playerName ? playerName : 'unknown entity' }}</h2>
  <p>
    <input type="text"/>
    <button>Set Name</button>
  </p>
</section>

// apps/countdown-game-react/src/app/components/player.tsx
import { useRef, useState } from 'react';

export default function Player() {
  const playerNameRef = useRef<HTMLInputElement>(null);
  const [playerName, setPlayerName] = useState('');

  function handleSubmit(): void {
    setPlayerName(playerNameRef.current?.value ?? '');
    if (playerNameRef.current) {
      playerNameRef.current.value = '';
    }
  }

  return (
    <section id="player">
      <h2>Welcome {playerName ? playerName : 'unknown entity'}</h2>
      <p>
        <input type="text" ref={playerNameRef} />
        <button onClick={handleSubmit}>Set Name</button>
      </p>
    </section>
  );
}
