// apps/countdown-game-angular/src/app/timer-challenge/timer-challenge.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  HostBinding,
  input,
  InputSignal,
  Signal,
  signal,
  ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { ResultModalComponent } from '../result-modal/result-modal.component';

@Component({
  selector: 'app-timer-challenge',
  standalone: true,
  imports: [CommonModule, ResultModalComponent],
  templateUrl: './timer-challenge.component.html',
  styleUrl: './timer-challenge.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TimerChallengeComponent {
  public title: InputSignal<string> = input.required<string>();
  public targetTimeSecs: InputSignal<number> = input.required<number>();
  public targetTimeMillis: Signal<number> = computed(
    () => this.targetTimeSecs() * 1000
  );

  protected timerStarted = signal<boolean>(false);

  private startTime = signal<number | undefined>(undefined);
  private stopTime = signal<number | undefined>(undefined);
  private durationTimeMillis = computed(() => {
    const start = this.startTime();
    const stop = this.stopTime();

    if (!start || !stop) {
      return undefined;
    }

    return stop - start;
  });

  protected remainingTimeMillis = computed(() => {
    const duration = this.durationTimeMillis();
    if (!duration) {
      return undefined;
    }

    return this.targetTimeMillis() - duration;
  });

  private timer?: number;

  @ViewChild(ResultModalComponent) resultModal!: ResultModalComponent;

  @HostBinding('class')
  protected get cssClass(): string {
    return 'challenge';
  }

  public constructor() {
    // effect(() => {
    //   if (this.startTime() && this.stopTime() && !this.timerStarted()) {
    //     this.resultModal.open();
    //   }
    // });
  }

  protected startTimer(): void {
    if (this.timer) {
      clearTimeout(this.timer);
    }

    this.timerStarted.set(true);
    this.startTime.set(Date.now());
    this.stopTime.set(undefined);

    this.timer = setTimeout(() => {
      this.stopTimer();
    }, this.targetTimeMillis());
  }

  protected stopTimer(): void {
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = undefined;
    }

    this.timerStarted.set(false);
    this.stopTime.set(Date.now());

    this.resultModal.open();
  }
}

<h2>{{ title() }}</h2>

<p class="challenge-time">
  {{ targetTimeSecs() }} second{{ targetTimeSecs() > 1 ? 's' : '' }}
</p>

<p>
  <button (click)="timerStarted() ? stopTimer() : startTimer()">
    {{ timerStarted() ? 'Stop' : 'Start' }} Challenge
  </button>
</p>

<p [ngClass]="{active: timerStarted()}">
  {{ timerStarted() ? 'Time is running...' : 'Timer inactive' }}
</p>

<app-result-modal [targetTimeMillis]="targetTimeMillis()" [remainingTimeMillis]="remainingTimeMillis()"></app-result-modal>

// apps/countdown-game-react/src/app/components/timer-challenge.tsx
import { useRef, useState } from 'react';
import ResultModal, { ResultModalRef } from './result-modal';

export default function TimerChallenge({
  title,
  targetTimeSecs,
}: {
  title: string;
  targetTimeSecs: number;
}) {
  const [timerStarted, setTimerStarted] = useState(false);

  const startTime = useRef<number | null>(null);
  const stopTime = useRef<number | null>(null);
  const timeout = useRef<NodeJS.Timeout | null>(null);
  const dialog = useRef<ResultModalRef>(null);
  const targetTimeMillis: number = targetTimeSecs * 1000;

  let durationTimeMillis: number | undefined;
  if (startTime.current && stopTime.current) {
    durationTimeMillis = stopTime.current - startTime.current;
  }

  let remainingTimeMillis: number | undefined;
  if (durationTimeMillis !== undefined) {
    remainingTimeMillis = targetTimeMillis - durationTimeMillis;
  }

  if (remainingTimeMillis !== undefined && dialog.current) {
    dialog.current.open();
  }

  function handleStart(): void {
    setTimerStarted(true);

    startTime.current = Date.now();
    stopTime.current = null;

    timeout.current = setTimeout(() => {
      stopTimer();
    }, targetTimeMillis);
  }

  function handleStop(): void {
    stopTimer();
  }

  function stopTimer(): void {
    clearTimeout(timeout.current ?? undefined);

    setTimerStarted(false);
    stopTime.current = Date.now();
  }

  return (
    <>
      <ResultModal
        ref={dialog}
        targetTimeMillis={targetTimeMillis}
        remainingTimeMillis={remainingTimeMillis}
      />
      <section className="challenge">
        <h2>{title}</h2>

        <p className="challenge-time">
          {targetTimeSecs} second{targetTimeSecs > 1 ? 's' : ''}
        </p>

        <p>
          <button onClick={timerStarted ? handleStop : handleStart}>
            {timerStarted ? 'Stop' : 'Start'} Challenge
          </button>
        </p>

        <p className={timerStarted ? 'active' : undefined}>
          {timerStarted ? 'Time is running...' : 'Timer inactive'}
        </p>
      </section>
    </>
  );
}
